name: app build
run-name: build apk
on:
 push:
  branches:
    - main
    - flutter
jobs:
  Flutter-App-Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_app
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'flutter'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.9'
    - run: flutter pub get
    - run: flutter build apk
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
